In [ ]:
i

In [24]:
import numpy as np
import spacy

nlp = spacy.load("en_core_web_sm")

def average_ambedding(sentence):
    doc = nlp(sentence)
    vectors = [token.vector for token in doc if token.has_vector]

    return np.mean(vectors, axis=0) if vectors else np.zeros((nlp.vocab.vectors_length))

sentence = "The  Dog run fast"
embedding = average_ambedding(sentence)
print(embedding[:6])

[ 0.22553973 -0.6751412  -0.6147562   0.08143897  0.2217906  -0.29508153]


In [ ]:
 0.22553973 -0.6751412  -0.6147562   0.08143897  0.2217906 

In [11]:
from sklearn.feature_extraction.text import TfidfVectorizer

## Sample corpus
corpus = [
    "the dog runs fast",
    "A cat sleeps on the sofa",
    "Dog and cats are great pets"
    
]

### compute if-idf scores

vectorizer = TfidfVectorizer()
vectorizer.fit(corpus)
tfidf_scores =  vectorizer.transform([sentence]).toarray()[0]
words = vectorizer.get_feature_names_out()

In [12]:
tfidf_scores

array([0.        , 0.        , 0.        , 0.        , 0.51785612,
       0.68091856, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.51785612])

In [13]:
words

array(['and', 'are', 'cat', 'cats', 'dog', 'fast', 'great', 'on', 'pets',
       'runs', 'sleeps', 'sofa', 'the'], dtype=object)

In [25]:
from sklearn.decomposition import PCA

sentence_embeddings = np.array([average_ambedding(sent) for sent in corpus])

pca = PCA()
reduced_embeddings = pca.fit_transform(sentence_embeddings)

In [26]:
print(reduced_embeddings)

[[ 1.0447967e+00 -1.4652990e+00  1.4922823e-07]
 [ 1.0035437e+00  1.4851063e+00  1.4922820e-07]
 [-2.0483403e+00 -1.9806856e-02  1.4922820e-07]]


In [33]:
!pip install sentence-transformers


Defaulting to user installation because normal site-packages is not writeable
   ---------------------------------------- 0.0/596.4 kB ? eta -:--:--
   ----------------------------------- ---- 524.3/596.4 kB 5.6 MB/s eta 0:00:01
   ---------------------------------------- 596.4/596.4 kB 2.4 MB/s eta 0:00:00


In [34]:
### Sentence transfrom

from sentence_transformers import SentenceTransformer


In [45]:
### NLP Task Sentence Similarity
import warnings
warnings.filterwarnings("ignore")

from sklearn.metrics.pairwise import cosine_similarity

# 1. Initialize the SentenceTransformer model
model = SentenceTransformer("all-MiniLM-L6-v2")

def compute_similarity(sentence1, sentence2):
    embedding1 = model.encode(sentence1)
    embedding2 = model.encode(sentence2)
    
    similarity_score = cosine_similarity([embedding1], [embedding2])[0][0]

    return similarity_score

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

In [48]:
# 2. Define sentences and test the function
sentence1 = "A dog is running in the park"
sentence2 = "A pup is playing in the park"

In [49]:
similarity = compute_similarity(sentence1, sentence2)

print(f"Sentence Similarity Score:{similarity:.4f}")



Sentence Similarity Score:0.8162
